config/routes.rb
Rails.application.routes.draw do
  get 'users/edit'

  root 'home#index'
  get 'dashboard',               to: 'home#show'
  get '/auth/twitter',           as: :login
  get '/logout',                 to: 'sessions#destroy'
  get '/auth/twitter/callback',  to: 'sessions#create'

  resources :users, only: [:edit, :update]
  resources :home, only: [:update]
  resources :teams, only: [:index, :show]
  resources :posts, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
end

app/views/partials/_activity_feed.html.erb
<h4 class="ui horizontal divider header">
  <i class="tag icon"></i>
  Activity Feed
</h4>

<%= render partial: 'partials/post_form' %>

<div class="ui feed">
  <% for activity in @activities %>
    <%= render_activity activity %>
  <% end %>
</div>

app/views/partials/_daily_game_alert.html.erb
<div class="ui card">
  <div class="content">
    <%= image_tag(favorite_team_info.image, class: "right floated mini ui image") %>
    <% if game_alert.message.nil? %>
      <div class="header">The <%= favorite_team_info.city %> <%= favorite_team_info.name %>  Play The <%= game_alert.opponent %> Today!</div>
    <% else %>
      <div class="header"><%= game_alert.message %></div>
    <% end %>
  </div>
  <div class="content">
    <% if game_alert.message.nil? %>
      <h4 class="ui sub header">vs. <%= game_alert.opponent %></h4>
    <% else %>
      <div></div>
    <% end %>
    <div class="meta"> </div>
    <div class="description">
      <% if game_alert.message.nil? %>
        <strong><%= game_alert.venue_name %></strong><br><br>
        <%= game_alert.venue_address %><br>
        <%= game_alert.venue_city %>, <%= game_alert.venue_state %> <%= game_alert.venue_zipcode %><br><br>
        Seen on: <strong><%= game_alert.broadcast %></strong> broadcast at<strong><%= game_alert.time_of_game %></strong>
      <% else %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_dashboard_modal.html.erb
<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">
    Please Pick your Favorite NBA Team and your Profile Description
  </div>
  <div class="content">
    <div class="ui form">
      <div class="field">
        <%= form_for(User.new, url: user_path(current_user.id), :html => { method: :patch }) do |f| %>
          <%= f.label "Favorite Team" %><br>
          <%= f.collection_select :favorite_team, FavoriteTeam.all, :id, :format_name_for_modal, { prompt: "Choose a favorite team" }, { id: "select"} %><br><br>
          <%= f.label 'Profile Description (optional)' %>
          <%= f.text_area :description, rows: 2 %><br><br>
          <%= f.submit "Update Profile", class: "ui blue button" %>
        <% end %>
        <div class="actions">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<% cache "footer-normal" do %>
<div class="ui vertical footer segment" id="normal">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="twelve wide column">
        <h3 class="ui header">SportsAddict</h3>
        <p>&copy; 2016 All rights reserved</p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_game_alert.html.erb
<div class="ui card">
  <div class="content">
    <%= image_tag('nuggets.gif', class: "right floated mini ui image") %>
    <!-- <img class="right floated mini ui image" src="/images/avatar/large/elliot.jpg"> -->
    <div class="header">
      The Nuggets play the Heat Tonight!
    </div>
    <div class="meta">
      7:30 pm MT @DEN
    </div>
    <div class="description">
      Seen on: <strong>ALT</strong>
    </div>
  </div>
</div>

app/views/partials/_game_stats.html.erb
<h4 class="ui horizontal divider header">
  <i class="trophy icon"></i>
  Game Summary
</h4>
  <%= render partial: 'partials/single_game_summary', locals: { all_game_stats: @all_game_stats } %>

<h4 class="ui horizontal divider header">
  <i class="bar chart icon"></i>
  Stat Leaders
</h4>
  <%= render partial: 'partials/single_game_stat_leaders', locals: { all_game_stats: @all_game_stats } %>

app/views/partials/_landing_footer.html.erb
<div class="ui inverted vertical footer segment" id="landing">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="twelve wide column">
        <h4 class="ui inverted header">SportsAddict</h4>
        <p>&copy; 2016 All rights reserved</p>
      </div>
    </div>
  </div>
</div>

app/views/partials/_nav_bar.html.erb
<% cache "nav-bar-normal" do %>
<div class="ui large fixed top menu">
  <div class="ui container">
    <%= link_to "SportsAddict", root_path, class: "item", id: "nav-logo-second" %>
    <div class="right menu">
      <%= link_to "Teams", teams_path, class: "ui item" %>
      <%= link_to "Dashboard", dashboard_path, class: "ui item" %>
      <%= link_to "Logout", logout_path, class: "ui item" %>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_post_form.html.erb
<div class="ui form">
  <div class="field">
    <%= form_for(Post.new, url: posts_path(@post)) do |f| %>
      <%= f.label :post %>
      <%= f.text_area :message, rows: 2 %><br><br>
      <%= f.submit "Post It", class: "ui right floated blue button" %>
      <% end %>
    </div>
</div>

app/views/partials/_profile_info.html.erb
<%= cache cache_for_profile(current_user) do %>
  <div class="ui card">
    <div class="content">
      <%= image_tag(user.profile_image, class: "right floated tiny ui image") %>
      <div class="header">
        <%= user.name %>
      </div>
      <div class="meta">
        <%= user.favorite_team.city %> <%= user.favorite_team.name %>
      </div>
      <div class="description">
        <%= user.description %>
      </div>
    </div>
      <%= link_to "Edit Profile", edit_user_path(current_user.id), class: "ui right floated blue button" %>
  </div>
<% end %>

app/views/partials/_schedule.html.erb
<h4 class="ui horizontal divider header">
  <i class="calendar icon"></i>
  NBA Schedule
</h4>
<h5><%= today_game_schedule[:date] %></h5>
<div class="ui relaxed divided list"><br>
  <div class="ui grid">
  <% today_game_schedule[:games].each do |game| %>
  <div class="seven wide column">
    <div class="column">
      <div class="ui segment">

    <div class="item">
      <div class="content"><br>
        <div class="header"><%= game[:away_team] %> @ <%= game[:home_team] %></div>
        <div class="meta">
          <span class="stay"> <strong><%= game[:time] %></strong></span>
        </div><br>
        <div class="description">
          <p>Seen on: <strong><%= game[:broadcast] %></strong></p>
        </div>
      </div>
    </div><br>
  </div>
  </div>
  </div>
    <% end %>
  </div>
</div>

app/views/partials/_single_game_stat_leaders.html.erb
<table class="ui definition table">
  <% if all_game_stats.home_team_name.nil? %>
    <strong><%= all_game_stats.no_game_message %></strong>
  <% else %>
  <thead>
    <tr><th></th>
    <th><%= all_game_stats.home_team_name %></th>
    <th></th>
    <th><%= all_game_stats.away_team_name %></th>
    <th></th>
  </tr></thead>
  <tbody>
    <tr>
      <td>PTS</td>
      <td><%= all_game_stats.home_team_stats_leaders.points_leader_name %></td>
      <td><%= all_game_stats.home_team_stats_leaders.points %></td>
      <td><%= all_game_stats.away_team_stats_leaders.points_leader_name %></td>
      <td><%= all_game_stats.away_team_stats_leaders.points %></td>
    </tr>
    <tr>
      <td>REB</td>
      <td><%= all_game_stats.home_team_stats_leaders.rebounds_leader_name %></td>
      <td><%= all_game_stats.home_team_stats_leaders.rebounds %></td>
      <td><%= all_game_stats.away_team_stats_leaders.rebounds_leader_name %></td>
      <td><%= all_game_stats.away_team_stats_leaders.rebounds %></td>
    </tr>
    <tr>
      <td>AST</td>
      <td><%= all_game_stats.home_team_stats_leaders.assists_leader_name %></td>
      <td><%= all_game_stats.home_team_stats_leaders.assists %></td>
      <td><%= all_game_stats.away_team_stats_leaders.assists_leader_name %></td>
      <td><%= all_game_stats.away_team_stats_leaders.assists %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/partials/_single_game_summary.html.erb
<table class="ui very basic table">
  <thead>
    <tr>
      <th></th>
      <% if all_game_stats.home_team_stats_by_quarter.nil? %>
        <th>Q1</th>
        <th>Q2</th>
        <th>Q3</th>
        <th>Q4</th>
      <% else %>
        <% all_game_stats.home_team_stats_by_quarter.each do |quarter| %>
          <th>Q<%= quarter.number %></th>
        <% end %>
          <th>Final</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if all_game_stats.home_team_name.nil? %>
      <tr>
        <td><strong><%= all_game_stats.no_game_message %></strong></td>
      </tr>
    <% else %>
      <tr>
        <td><%= all_game_stats.home_team_name %></td>
        <% all_game_stats.home_team_stats_by_quarter.each do |quarter| %>
          <td><%= quarter.points%></td>
        <% end %>
        <td><%= all_game_stats.home_team_total_points %></td>
      </tr>
      <tr>
        <td><%= all_game_stats.away_team_name %></td>
        <% all_game_stats.away_team_stats_by_quarter.each do |quarter| %>
          <td><%= quarter.points %></td>
        <% end %>
        <td><%= all_game_stats.away_team_total_points %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_standings.html.erb
<div class="ui card">
  <div class="content">
    <i class="header">Standings</i>
    <div class="meta">
      <%= favorite_team_division %> Division
    </div>
  </div>
  <div class="content">
    <table class="ui very basic collapsing celled table">
      <thead>
        <tr><th>Teams</th>
        <th>W-L</th>
      </tr></thead>
      <tbody>
        <% standings.each do |standing| %>
        <tr>
          <td>
            <h4 class="ui image header">
              <%= image_tag(standing.image) %>
              <div class="content">
                <%= standing.city %>
                <div class="sub header"><%= standing.name %>
              </div>
            </div>
          </h4></td>
          <td>
            <%= standing.record %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>