config/routes.rb
Rails.application.routes.draw do
  get 'users/edit'

  root 'home#index'
  get 'dashboard',               to: 'home#show'
  get '/auth/twitter',           as: :login
  get '/logout',                 to: 'sessions#destroy'
  get '/auth/twitter/callback',  to: 'sessions#create'

  resources :users, only: [:edit, :update]
  resources :home, only: [:update]
  resources :teams, only: [:index, :show]
  resources :posts, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :create_enricher

  def index
  end

  def show
    @user = current_user

    if @user.favorite_team.nil?
      @pick_favorite_team = true
      @favorite_team      = FavoriteTeam.all
    else
      @standings              = Standing.standings(favorite_team)
      @favorite_team_division = FavoriteTeam.division(favorite_team)
      @team_info              = FavoriteTeam.favorite_team_info(favorite_team)
      @game_alert_info        = GameStat.game_alert_info(favorite_team)
      @all_game_stats         = GameStat.all_game_stats(favorite_team)
      @today_game_schedule    = GameStat.scheduled_games_today
      @activities             = stream_feed(current_user.id)
    end
  end


  private

    def favorite_team
      current_user.favorite_team.name
    end

    def stream_feed(current_user_id)
      feed         ||= StreamRails.feed_manager.get_news_feeds(current_user_id)[:flat]
      results      = feed.get(limit: 10)['results']
      @activities  = @enricher.enrich_activities(results)
    end

    def create_enricher
      @enricher = StreamRails::Enrich.new
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<html>
  <body id="layout">
    <div class="ui large top fixed hidden menu">
      <div class="ui container">
        <%= link_to "SportsAddict", root_path, class: "item", id: "nav-logo-second" %>
        <div class="right menu">
          <div class="item">
            <% if current_user %>
              <%= link_to "Logout", logout_path, class: "ui inverted blue button" %>
            <% else %>
              <%= link_to "Login", login_path, class: "ui inverted blue button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <div class="ui vertical inverted sidebar menu">
      <% if current_user %>
        <%= link_to "Logout", logout_path, class: "item" %>
      <% else %>
        <%= link_to "Login", login_path, class: "item" %>
      <% end %>
    </div>


    <!-- Page Contents -->
    <div class="pusher">
      <div class="ui inverted vertical masthead center aligned segment">

        <div class="ui container">
          <div class="ui large secondary inverted pointing menu">
            <a class="toc item">
              <i class="sidebar icon"></i>
            </a>
            <%= link_to "SportsAddict", root_path, class: "item", id: "nav-logo" %>
          </div>
        </div>

        <div class="ui text container">
          <h2 class="ui inverted header">
            Enjoy the game the <strong>Right</strong> way!
          </h2>
          <h2></h2>
          <% if current_user %>
            <%= link_to "Dashboard", dashboard_path, class: "ui huge blue button" %>
          <% else %>
            <p><strong>Login</strong> with </p>
            <%= link_to login_path, class: "ui huge twitter button" do %>
              <i class="twitter icon"></i>Twitter
            <% end %>
          <% end %>
        </div>
      </div>


      <div class="ui vertical stripe segment">
        <div class="ui text container">
          <h3 class="ui header">Real-Time Stats</h3>
          <p>Keep up with your favorite teams stats in real time, while you chat on your news feed with other fans!</p>
          <h4 class="ui horizontal header divider">
            Stay in the Game
          </h4>
          <h3 class="ui header">What team has the most support?</h3>
          <p>Follow your fellow fans to see what they have to say about the games. Or follow your rivals and talk as much trash as you want! Its all fun!</p>
        </div>
      </div>

      <%= render partial: 'partials/landing_footer' %>
    </div>
  </body>
</html>

app/views/home/show.html.erb
<% if @pick_favorite_team %>
  <html>
    <body>
      <%= render partial: 'partials/dashboard_modal', locals: { user: @user, favorite_teams: @favorite_teams } %>
    </body>
  </html>
<% else %>
  <br><br><br><br><br>
  <body>
    <div class="ui container">
      <div class="ui equal width grid">
        <div class="row">
          <div class="column">
            <div class="ui segment">
              <%= render partial: 'partials/profile_info', locals: { user: @user } %>
            </div>
            <div class="ui segment">
              <%= render partial: 'partials/standings', locals: { standings: @standings, favorite_team_division: @favorite_team_division, team_image: @team_image } %>
            </div>
          </div>

          <div class="seven wide column">
            <div class="ui segment">
              <%= render partial: 'partials/game_stats', locals: { all_game_stats: @all_game_stats } %>
            </div>
            <div class="ui segment">
              <%= render partial: 'partials/activity_feed', locals: { activities: @activities } %>
            </div>
          </div>

          <div class="column">
            <div class="ui segment">
              <%= render partial: 'partials/daily_game_alert', locals: { game_alert: @game_alert_info, favorite_team_info: @team_info } %>
            </div>
            <div class="ui segment">
              <%= render partial: 'partials/schedule', locals: { today_game_schedule: @today_game_schedule } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
<% end %>